<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.267" timestamp="2022-12-15T17:00:16.358151" hostname="LAPTOP-I0MC04RM"><testcase classname="" name="cards_proj.tests.test_cli" time="0.000"><error message="collection failure">ImportError while importing test module '/home/janvandenbrand/repos/python-testing-with-pytest/cards_proj/tests/test_cli.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../.local/lib/python3.8/site-packages/_pytest/python.py:578: in _importtestmodule
    mod = import_path(self.fspath, mode=importmode)
../../.local/lib/python3.8/site-packages/_pytest/pathlib.py:524: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1014: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:991: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:975: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:671: in _load_unlocked
    ???
../../.local/lib/python3.8/site-packages/_pytest/assertion/rewrite.py:170: in exec_module
    exec(co, module.__dict__)
cards_proj/tests/test_cli.py:3: in &lt;module&gt;
    import cards
E   ModuleNotFoundError: No module named 'cards'</error></testcase></testsuite></testsuites>